### ISSUE TITLE
Collision check on server side

### ISSUE THREAD

**Issue by ShakeShadow** [WeibelLab-Teaching/CSE_218_118_Fa20_Team_N#14]

**Comment by goldsail** [comment]
On Nov 14 evening, Shanshan and I discussed about multiplayer framework. We implemented a multiplayer prototype using Colyseus. The synchronization model is two-way: The clients send their actions to the server. The server calculates their new states, and sends them back to the clients. 

The problem is, this model requires the collision detection on the server side, because the new states are calculated only on the server side. There is a promise to the client that the server will always send back **legal** states. We cannot do it on the client side, because the client does not hold the **real-time** state. Due to latency, the client state is always behind the authoritative server state.

I raise this issue because, as far as I know, the current approach is to do this on the client side. 

We have a possible solution to this: put a binary (bi-color) image on the server (like a screenshot of the 3D maze model). The server uses this image to determine if a new position is legal (no collision with wall) or not, and adjust the actions accordingly.
